# docker-compose.yaml
# ref: https://www.cloudbees.com/blog/how-to-install-and-run-jenkins-with-docker-compose
version: '3.8'

services:
  jenkins:
    build: .
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

#user: admin
#password: jenkinsadmin